[daemons.relay]
env = { RUST_BACKTRACE = "full" }
run = "mise run relay:run"

[daemons.web]
dir = "vendor/moq/demo"
run = "just web"

[daemons.publish-shrek]
run = "mise run stream:file --name public/shrek"

[daemons.publish-another-shrek]
run = "mise run stream:file --name bbb/another-shrek"

[daemons.stream-obs-h264]
run = "mise run stream:obs moq-local-h264"

[daemons.stream-obs-h265]
run = "mise run stream:obs moq-local-h265"

[daemons.stream-obs-av1]
run = "mise run stream:obs moq-local-av1"
