import Foundation

// VideoConfig, AudioConfig, and AnnouncedInfo are generated by UniFFI into moq.swift.

// MARK: - Frame

public struct MoQFrame: Sendable {
    public let payload: Data
    public let timestampUs: UInt64
    public let keyframe: Bool
}

// MARK: - Catalog Subscription

public final class MoQCatalogSubscription: Sendable {
    public let catalogs: AsyncStream<MoQCatalog>
    private let cont: AsyncStream<MoQCatalog>.Continuation
    private let subscriptionHandle: UInt32

    init(broadcastHandle: UInt32) throws {
        var continuation: AsyncStream<MoQCatalog>.Continuation!
        catalogs = AsyncStream<MoQCatalog> { continuation = $0 }
        cont = continuation

        let cb = CatalogCB(continuation: continuation)
        subscriptionHandle = try moqConsumeCatalog(broadcast: broadcastHandle, callback: cb)

        continuation.onTermination = { @Sendable [subscriptionHandle] _ in
            try? moqConsumeClose(consume: subscriptionHandle)
        }
    }
}

private final class CatalogCB: CatalogCallback {
    private let continuation: AsyncStream<MoQCatalog>.Continuation

    init(continuation: AsyncStream<MoQCatalog>.Continuation) {
        self.continuation = continuation
    }

    func onCatalog(catalogId: UInt32) {
        continuation.yield(MoQCatalog(handle: catalogId))
    }
}

// MARK: - Catalog

public final class MoQCatalog: Sendable {
    public let handle: UInt32

    fileprivate init(handle: UInt32) {
        self.handle = handle
    }

    public static func subscribe(broadcastHandle: UInt32) async throws -> MoQCatalog {
        let subscription = try MoQCatalogSubscription(broadcastHandle: broadcastHandle)
        var iterator = subscription.catalogs.makeAsyncIterator()
        guard let first = await iterator.next() else {
            throw MoqError.Error(msg: "No catalog received")
        }
        return first
    }

    public static func subscribeUpdates(broadcastHandle: UInt32) throws -> MoQCatalogSubscription {
        return try MoQCatalogSubscription(broadcastHandle: broadcastHandle)
    }

    public func videoConfig(at index: UInt32) throws -> VideoConfig {
        try moqConsumeVideoConfig(catalog: handle, index: index)
    }

    public func audioConfig(at index: UInt32) throws -> AudioConfig {
        try moqConsumeAudioConfig(catalog: handle, index: index)
    }

    public func close() {
        try? moqConsumeCatalogClose(catalog: handle)
    }

    deinit {
        try? moqConsumeCatalogClose(catalog: handle)
    }
}
