import Foundation

// MoqVideoRendition, MoqAudioRendition, MoqCatalog, AnnouncedInfo, and FrameData
// are generated by UniFFI into MoQ.swift.

extension MoqVideoRendition: CustomDebugStringConvertible {
    public var debugDescription: String {
        return "codec=\(codec), width=\(codedWidth ?? 0), height=\(codedHeight ?? 0)"
    }
}

extension MoqAudioRendition: CustomDebugStringConvertible {
    public var debugDescription: String {
        return "codec=\(codec), sampleRate=\(sampleRate), channels=\(channelCount)"
    }
}

// MARK: - Track Info Types

public protocol MoQTrackInfo: Sendable {
    var name: String { get }
}

public struct MoQVideoTrackInfo: MoQTrackInfo, @unchecked Sendable {
    public let name: String
    public let config: MoqVideoRendition
    let broadcast: MoqBroadcast

    public init(name: String, config: MoqVideoRendition, broadcast: MoqBroadcast) {
        self.name = name
        self.config = config
        self.broadcast = broadcast
    }
}

public struct MoQAudioTrackInfo: MoQTrackInfo, @unchecked Sendable {
    public let name: String
    public let config: MoqAudioRendition
    let broadcast: MoqBroadcast

    public init(name: String, config: MoqAudioRendition, broadcast: MoqBroadcast) {
        self.name = name
        self.config = config
        self.broadcast = broadcast
    }
}

/// Describes the tracks available in the current live broadcast.
public struct MoQBroadcastInfo: Sendable {
    public let path: String
    public let videoTracks: [MoQVideoTrackInfo]
    public let audioTracks: [MoQAudioTrackInfo]
}

/// Lifecycle events emitted on the broadcasts stream.
public enum MoQBroadcastEvent: Sendable {
    case available(MoQBroadcastInfo)
    case unavailable(path: String)
}

// MARK: - Frame

public struct MoQFrame: Sendable {
    public let payload: Data
    public let timestampUs: UInt64
    public let keyframe: Bool
}
