import Foundation

// MoqVideo, MoqAudio, MoqCatalog, MoqFrame, and MoqDimensions
// are generated by UniFFI into MoQ.swift.

extension MoqVideo: CustomDebugStringConvertible {
    public var debugDescription: String {
        return "codec=\(codec), width=\(coded?.width ?? 0), height=\(coded?.height ?? 0)"
    }
}

extension MoqAudio: CustomDebugStringConvertible {
    public var debugDescription: String {
        return "codec=\(codec), sampleRate=\(sampleRate), channels=\(channelCount)"
    }
}

// MARK: - Track Info Types

public protocol MoQTrackInfo: Sendable {
    var name: String { get }
}

public struct MoQVideoTrackInfo: MoQTrackInfo, @unchecked Sendable {
    public let name: String
    public let config: MoqVideo
    let broadcast: MoqBroadcastConsumer

    public init(name: String, config: MoqVideo, broadcast: MoqBroadcastConsumer) {
        self.name = name
        self.config = config
        self.broadcast = broadcast
    }
}

public struct MoQAudioTrackInfo: MoQTrackInfo, @unchecked Sendable {
    public let name: String
    public let config: MoqAudio
    let broadcast: MoqBroadcastConsumer

    public init(name: String, config: MoqAudio, broadcast: MoqBroadcastConsumer) {
        self.name = name
        self.config = config
        self.broadcast = broadcast
    }
}

/// Describes the tracks available in the current live broadcast.
public struct MoQBroadcastInfo: Sendable {
    public let path: String
    public let videoTracks: [MoQVideoTrackInfo]
    public let audioTracks: [MoQAudioTrackInfo]
}

/// Lifecycle events emitted on the broadcasts stream.
public enum MoQBroadcastEvent: Sendable {
    case available(MoQBroadcastInfo)
    case unavailable(path: String)
}
