// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(moqFFI)
import moqFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_moq_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_moq_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMoqFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MoqAnnouncedProtocol: AnyObject, Sendable {
    
    /**
     * Get the next broadcast announcement. Returns `None` when the origin is closed.
     */
    func next() async throws  -> AnnouncedInfo?
    
}
open class MoqAnnounced: MoqAnnouncedProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqannounced(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqannounced(handle, $0) }
    }

    

    
    /**
     * Get the next broadcast announcement. Returns `None` when the origin is closed.
     */
open func next()async throws  -> AnnouncedInfo?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqannounced_next(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_moq_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_moq_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeAnnouncedInfo.lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqAnnounced: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqAnnounced

    public static func lift(_ handle: UInt64) throws -> MoqAnnounced {
        return MoqAnnounced(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqAnnounced) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqAnnounced {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqAnnounced, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqAnnounced_lift(_ handle: UInt64) throws -> MoqAnnounced {
    return try FfiConverterTypeMoqAnnounced.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqAnnounced_lower(_ value: MoqAnnounced) -> UInt64 {
    return FfiConverterTypeMoqAnnounced.lower(value)
}






public protocol MoqBroadcastProtocol: AnyObject, Sendable {
    
    /**
     * Create a catalog consumer for this broadcast.
     */
    func catalog() async throws  -> MoqCatalogStream
    
    /**
     * Subscribe to a track by name, delivering frames in decode order.
     *
     * `max_latency_ms` controls the maximum buffering before skipping a GoP.
     */
    func subscribeTrack(name: String, maxLatencyMs: UInt64) async throws  -> MoqTrack
    
}
open class MoqBroadcast: MoqBroadcastProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqbroadcast(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqbroadcast(handle, $0) }
    }

    

    
    /**
     * Create a catalog consumer for this broadcast.
     */
open func catalog()async throws  -> MoqCatalogStream  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqbroadcast_catalog(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_u64,
            completeFunc: ffi_moq_ffi_rust_future_complete_u64,
            freeFunc: ffi_moq_ffi_rust_future_free_u64,
            liftFunc: FfiConverterTypeMoqCatalogStream_lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    
    /**
     * Subscribe to a track by name, delivering frames in decode order.
     *
     * `max_latency_ms` controls the maximum buffering before skipping a GoP.
     */
open func subscribeTrack(name: String, maxLatencyMs: UInt64)async throws  -> MoqTrack  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqbroadcast_subscribe_track(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(name),FfiConverterUInt64.lower(maxLatencyMs)
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_u64,
            completeFunc: ffi_moq_ffi_rust_future_complete_u64,
            freeFunc: ffi_moq_ffi_rust_future_free_u64,
            liftFunc: FfiConverterTypeMoqTrack_lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqBroadcast: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqBroadcast

    public static func lift(_ handle: UInt64) throws -> MoqBroadcast {
        return MoqBroadcast(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqBroadcast) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqBroadcast {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqBroadcast, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqBroadcast_lift(_ handle: UInt64) throws -> MoqBroadcast {
    return try FfiConverterTypeMoqBroadcast.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqBroadcast_lower(_ value: MoqBroadcast) -> UInt64 {
    return FfiConverterTypeMoqBroadcast.lower(value)
}






public protocol MoqCatalogStreamProtocol: AnyObject, Sendable {
    
    /**
     * Get the next catalog update. Returns `None` when the track ends.
     */
    func next() async throws  -> MoqCatalog?
    
}
open class MoqCatalogStream: MoqCatalogStreamProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqcatalogstream(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqcatalogstream(handle, $0) }
    }

    

    
    /**
     * Get the next catalog update. Returns `None` when the track ends.
     */
open func next()async throws  -> MoqCatalog?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqcatalogstream_next(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_moq_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_moq_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeMoqCatalog.lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqCatalogStream: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqCatalogStream

    public static func lift(_ handle: UInt64) throws -> MoqCatalogStream {
        return MoqCatalogStream(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqCatalogStream) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqCatalogStream {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqCatalogStream, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqCatalogStream_lift(_ handle: UInt64) throws -> MoqCatalogStream {
    return try FfiConverterTypeMoqCatalogStream.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqCatalogStream_lower(_ value: MoqCatalogStream) -> UInt64 {
    return FfiConverterTypeMoqCatalogStream.lower(value)
}






public protocol MoqMediaProtocol: AnyObject, Sendable {
    
    /**
     * Finish this media track and finalize encoding.
     */
    func finish() throws 
    
    /**
     * Write a frame to this media track.
     *
     * `timestamp_us` is the presentation timestamp in microseconds.
     */
    func writeFrame(payload: Data, timestampUs: UInt64) throws 
    
}
open class MoqMedia: MoqMediaProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqmedia(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqmedia(handle, $0) }
    }

    

    
    /**
     * Finish this media track and finalize encoding.
     */
open func finish()throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_method_moqmedia_finish(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Write a frame to this media track.
     *
     * `timestamp_us` is the presentation timestamp in microseconds.
     */
open func writeFrame(payload: Data, timestampUs: UInt64)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_method_moqmedia_write_frame(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(payload),
        FfiConverterUInt64.lower(timestampUs),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqMedia: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqMedia

    public static func lift(_ handle: UInt64) throws -> MoqMedia {
        return MoqMedia(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqMedia) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqMedia {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqMedia, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqMedia_lift(_ handle: UInt64) throws -> MoqMedia {
    return try FfiConverterTypeMoqMedia.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqMedia_lower(_ value: MoqMedia) -> UInt64 {
    return FfiConverterTypeMoqMedia.lower(value)
}






public protocol MoqOriginProtocol: AnyObject, Sendable {
    
    /**
     * Subscribe to broadcast announcements on this origin.
     */
    func announced()  -> MoqAnnounced
    
    /**
     * Consume a broadcast from this origin by path.
     */
    func consume(path: String) throws  -> MoqBroadcast
    
    /**
     * Publish a broadcast to this origin under the given path.
     */
    func publish(path: String, broadcast: MoqPublisher) throws 
    
}
open class MoqOrigin: MoqOriginProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqorigin(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqorigin(handle, $0) }
    }

    

    
    /**
     * Subscribe to broadcast announcements on this origin.
     */
open func announced() -> MoqAnnounced  {
    return try!  FfiConverterTypeMoqAnnounced_lift(try! rustCall() {
    uniffi_moq_ffi_fn_method_moqorigin_announced(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Consume a broadcast from this origin by path.
     */
open func consume(path: String)throws  -> MoqBroadcast  {
    return try  FfiConverterTypeMoqBroadcast_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_method_moqorigin_consume(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Publish a broadcast to this origin under the given path.
     */
open func publish(path: String, broadcast: MoqPublisher)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_method_moqorigin_publish(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterTypeMoqPublisher_lower(broadcast),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqOrigin: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqOrigin

    public static func lift(_ handle: UInt64) throws -> MoqOrigin {
        return MoqOrigin(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqOrigin) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqOrigin {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqOrigin, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqOrigin_lift(_ handle: UInt64) throws -> MoqOrigin {
    return try FfiConverterTypeMoqOrigin.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqOrigin_lower(_ value: MoqOrigin) -> UInt64 {
    return FfiConverterTypeMoqOrigin.lower(value)
}






public protocol MoqPublisherProtocol: AnyObject, Sendable {
    
    /**
     * Create a new media track for this broadcast.
     *
     * `format` controls the encoding of `init` and frame payloads.
     */
    func mediaOrdered(format: String, `init`: Data) throws  -> MoqMedia
    
}
open class MoqPublisher: MoqPublisherProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqpublisher(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqpublisher(handle, $0) }
    }

    

    
    /**
     * Create a new media track for this broadcast.
     *
     * `format` controls the encoding of `init` and frame payloads.
     */
open func mediaOrdered(format: String, `init`: Data)throws  -> MoqMedia  {
    return try  FfiConverterTypeMoqMedia_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_method_moqpublisher_media_ordered(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(format),
        FfiConverterData.lower(`init`),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqPublisher: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqPublisher

    public static func lift(_ handle: UInt64) throws -> MoqPublisher {
        return MoqPublisher(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqPublisher) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqPublisher {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqPublisher, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqPublisher_lift(_ handle: UInt64) throws -> MoqPublisher {
    return try FfiConverterTypeMoqPublisher.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqPublisher_lower(_ value: MoqPublisher) -> UInt64 {
    return FfiConverterTypeMoqPublisher.lower(value)
}






public protocol MoqSessionProtocol: AnyObject, Sendable {
    
    /**
     * Wait until the session is closed.
     */
    func closed() async throws 
    
    /**
     * Disconnect the session.
     */
    func disconnect() 
    
}
open class MoqSession: MoqSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqsession(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqsession(handle, $0) }
    }

    

    
    /**
     * Wait until the session is closed.
     */
open func closed()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqsession_closed(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_void,
            completeFunc: ffi_moq_ffi_rust_future_complete_void,
            freeFunc: ffi_moq_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    
    /**
     * Disconnect the session.
     */
open func disconnect()  {try! rustCall() {
    uniffi_moq_ffi_fn_method_moqsession_disconnect(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqSession

    public static func lift(_ handle: UInt64) throws -> MoqSession {
        return MoqSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqSession_lift(_ handle: UInt64) throws -> MoqSession {
    return try FfiConverterTypeMoqSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqSession_lower(_ value: MoqSession) -> UInt64 {
    return FfiConverterTypeMoqSession.lower(value)
}






public protocol MoqTrackProtocol: AnyObject, Sendable {
    
    /**
     * Get the next frame. Returns `None` when the track ends or is closed.
     */
    func next() async throws  -> FrameData?
    
    /**
     * Unsubscribe from this track, causing any pending `next()` call to return `None`.
     */
    func unsubscribe() 
    
}
open class MoqTrack: MoqTrackProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_moq_ffi_fn_clone_moqtrack(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_moq_ffi_fn_free_moqtrack(handle, $0) }
    }

    

    
    /**
     * Get the next frame. Returns `None` when the track ends or is closed.
     */
open func next()async throws  -> FrameData?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_method_moqtrack_next(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_moq_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_moq_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeFrameData.lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
    
    /**
     * Unsubscribe from this track, causing any pending `next()` call to return `None`.
     */
open func unsubscribe()  {try! rustCall() {
    uniffi_moq_ffi_fn_method_moqtrack_unsubscribe(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqTrack: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MoqTrack

    public static func lift(_ handle: UInt64) throws -> MoqTrack {
        return MoqTrack(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MoqTrack) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqTrack {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MoqTrack, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqTrack_lift(_ handle: UInt64) throws -> MoqTrack {
    return try FfiConverterTypeMoqTrack.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqTrack_lower(_ value: MoqTrack) -> UInt64 {
    return FfiConverterTypeMoqTrack.lower(value)
}




/**
 * A broadcast announced by an origin.
 */
public struct AnnouncedInfo: Equatable, Hashable {
    public var path: String
    public var active: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, active: Bool) {
        self.path = path
        self.active = active
    }

    

    
}

#if compiler(>=6)
extension AnnouncedInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnnouncedInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnnouncedInfo {
        return
            try AnnouncedInfo(
                path: FfiConverterString.read(from: &buf), 
                active: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AnnouncedInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterBool.write(value.active, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnouncedInfo_lift(_ buf: RustBuffer) throws -> AnnouncedInfo {
    return try FfiConverterTypeAnnouncedInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnouncedInfo_lower(_ value: AnnouncedInfo) -> RustBuffer {
    return FfiConverterTypeAnnouncedInfo.lower(value)
}


/**
 * A decoded media frame.
 */
public struct FrameData: Equatable, Hashable {
    public var payload: Data
    public var timestampUs: UInt64
    public var keyframe: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(payload: Data, timestampUs: UInt64, keyframe: Bool) {
        self.payload = payload
        self.timestampUs = timestampUs
        self.keyframe = keyframe
    }

    

    
}

#if compiler(>=6)
extension FrameData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrameData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrameData {
        return
            try FrameData(
                payload: FfiConverterData.read(from: &buf), 
                timestampUs: FfiConverterUInt64.read(from: &buf), 
                keyframe: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FrameData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterUInt64.write(value.timestampUs, into: &buf)
        FfiConverterBool.write(value.keyframe, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameData_lift(_ buf: RustBuffer) throws -> FrameData {
    return try FfiConverterTypeFrameData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameData_lower(_ value: FrameData) -> RustBuffer {
    return FfiConverterTypeFrameData.lower(value)
}


public struct MoqAudioRendition: Equatable, Hashable {
    public var codec: String
    public var description: Data?
    public var sampleRate: UInt32
    public var channelCount: UInt32
    public var bitrate: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(codec: String, description: Data?, sampleRate: UInt32, channelCount: UInt32, bitrate: UInt64?) {
        self.codec = codec
        self.description = description
        self.sampleRate = sampleRate
        self.channelCount = channelCount
        self.bitrate = bitrate
    }

    

    
}

#if compiler(>=6)
extension MoqAudioRendition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqAudioRendition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqAudioRendition {
        return
            try MoqAudioRendition(
                codec: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionData.read(from: &buf), 
                sampleRate: FfiConverterUInt32.read(from: &buf), 
                channelCount: FfiConverterUInt32.read(from: &buf), 
                bitrate: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MoqAudioRendition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.codec, into: &buf)
        FfiConverterOptionData.write(value.description, into: &buf)
        FfiConverterUInt32.write(value.sampleRate, into: &buf)
        FfiConverterUInt32.write(value.channelCount, into: &buf)
        FfiConverterOptionUInt64.write(value.bitrate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqAudioRendition_lift(_ buf: RustBuffer) throws -> MoqAudioRendition {
    return try FfiConverterTypeMoqAudioRendition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqAudioRendition_lower(_ value: MoqAudioRendition) -> RustBuffer {
    return FfiConverterTypeMoqAudioRendition.lower(value)
}


public struct MoqCatalog: Equatable, Hashable {
    public var video: [String: MoqVideoRendition]
    public var audio: [String: MoqAudioRendition]
    public var displayWidth: UInt32?
    public var displayHeight: UInt32?
    public var rotation: Double?
    public var flip: Bool?
    public var user: MoqUser?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(video: [String: MoqVideoRendition], audio: [String: MoqAudioRendition], displayWidth: UInt32?, displayHeight: UInt32?, rotation: Double?, flip: Bool?, user: MoqUser?) {
        self.video = video
        self.audio = audio
        self.displayWidth = displayWidth
        self.displayHeight = displayHeight
        self.rotation = rotation
        self.flip = flip
        self.user = user
    }

    

    
}

#if compiler(>=6)
extension MoqCatalog: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqCatalog: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqCatalog {
        return
            try MoqCatalog(
                video: FfiConverterDictionaryStringTypeMoqVideoRendition.read(from: &buf), 
                audio: FfiConverterDictionaryStringTypeMoqAudioRendition.read(from: &buf), 
                displayWidth: FfiConverterOptionUInt32.read(from: &buf), 
                displayHeight: FfiConverterOptionUInt32.read(from: &buf), 
                rotation: FfiConverterOptionDouble.read(from: &buf), 
                flip: FfiConverterOptionBool.read(from: &buf), 
                user: FfiConverterOptionTypeMoqUser.read(from: &buf)
        )
    }

    public static func write(_ value: MoqCatalog, into buf: inout [UInt8]) {
        FfiConverterDictionaryStringTypeMoqVideoRendition.write(value.video, into: &buf)
        FfiConverterDictionaryStringTypeMoqAudioRendition.write(value.audio, into: &buf)
        FfiConverterOptionUInt32.write(value.displayWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.displayHeight, into: &buf)
        FfiConverterOptionDouble.write(value.rotation, into: &buf)
        FfiConverterOptionBool.write(value.flip, into: &buf)
        FfiConverterOptionTypeMoqUser.write(value.user, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqCatalog_lift(_ buf: RustBuffer) throws -> MoqCatalog {
    return try FfiConverterTypeMoqCatalog.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqCatalog_lower(_ value: MoqCatalog) -> RustBuffer {
    return FfiConverterTypeMoqCatalog.lower(value)
}


public struct MoqUser: Equatable, Hashable {
    public var id: String?
    public var name: String?
    public var avatar: String?
    public var color: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String?, name: String?, avatar: String?, color: String?) {
        self.id = id
        self.name = name
        self.avatar = avatar
        self.color = color
    }

    

    
}

#if compiler(>=6)
extension MoqUser: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqUser {
        return
            try MoqUser(
                id: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                avatar: FfiConverterOptionString.read(from: &buf), 
                color: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MoqUser, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.avatar, into: &buf)
        FfiConverterOptionString.write(value.color, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqUser_lift(_ buf: RustBuffer) throws -> MoqUser {
    return try FfiConverterTypeMoqUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqUser_lower(_ value: MoqUser) -> RustBuffer {
    return FfiConverterTypeMoqUser.lower(value)
}


public struct MoqVideoRendition: Equatable, Hashable {
    public var codec: String
    public var description: Data?
    public var codedWidth: UInt32?
    public var codedHeight: UInt32?
    public var displayRatioWidth: UInt32?
    public var displayRatioHeight: UInt32?
    public var bitrate: UInt64?
    public var framerate: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(codec: String, description: Data?, codedWidth: UInt32?, codedHeight: UInt32?, displayRatioWidth: UInt32?, displayRatioHeight: UInt32?, bitrate: UInt64?, framerate: Double?) {
        self.codec = codec
        self.description = description
        self.codedWidth = codedWidth
        self.codedHeight = codedHeight
        self.displayRatioWidth = displayRatioWidth
        self.displayRatioHeight = displayRatioHeight
        self.bitrate = bitrate
        self.framerate = framerate
    }

    

    
}

#if compiler(>=6)
extension MoqVideoRendition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqVideoRendition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqVideoRendition {
        return
            try MoqVideoRendition(
                codec: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionData.read(from: &buf), 
                codedWidth: FfiConverterOptionUInt32.read(from: &buf), 
                codedHeight: FfiConverterOptionUInt32.read(from: &buf), 
                displayRatioWidth: FfiConverterOptionUInt32.read(from: &buf), 
                displayRatioHeight: FfiConverterOptionUInt32.read(from: &buf), 
                bitrate: FfiConverterOptionUInt64.read(from: &buf), 
                framerate: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: MoqVideoRendition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.codec, into: &buf)
        FfiConverterOptionData.write(value.description, into: &buf)
        FfiConverterOptionUInt32.write(value.codedWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.codedHeight, into: &buf)
        FfiConverterOptionUInt32.write(value.displayRatioWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.displayRatioHeight, into: &buf)
        FfiConverterOptionUInt64.write(value.bitrate, into: &buf)
        FfiConverterOptionDouble.write(value.framerate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqVideoRendition_lift(_ buf: RustBuffer) throws -> MoqVideoRendition {
    return try FfiConverterTypeMoqVideoRendition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqVideoRendition_lower(_ value: MoqVideoRendition) -> RustBuffer {
    return FfiConverterTypeMoqVideoRendition.lower(value)
}


/**
 * Error returned by all UniFFI-exported functions.
 */
public enum MoqError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Error(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MoqError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqError: FfiConverterRustBuffer {
    typealias SwiftType = MoqError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Error(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MoqError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Error(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqError_lift(_ buf: RustBuffer) throws -> MoqError {
    return try FfiConverterTypeMoqError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqError_lower(_ value: MoqError) -> RustBuffer {
    return FfiConverterTypeMoqError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMoqOrigin: FfiConverterRustBuffer {
    typealias SwiftType = MoqOrigin?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMoqOrigin.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMoqOrigin.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAnnouncedInfo: FfiConverterRustBuffer {
    typealias SwiftType = AnnouncedInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAnnouncedInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAnnouncedInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFrameData: FfiConverterRustBuffer {
    typealias SwiftType = FrameData?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFrameData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFrameData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMoqCatalog: FfiConverterRustBuffer {
    typealias SwiftType = MoqCatalog?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMoqCatalog.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMoqCatalog.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMoqUser: FfiConverterRustBuffer {
    typealias SwiftType = MoqUser?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMoqUser.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMoqUser.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeMoqAudioRendition: FfiConverterRustBuffer {
    public static func write(_ value: [String: MoqAudioRendition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeMoqAudioRendition.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: MoqAudioRendition] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: MoqAudioRendition]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeMoqAudioRendition.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeMoqVideoRendition: FfiConverterRustBuffer {
    public static func write(_ value: [String: MoqVideoRendition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeMoqVideoRendition.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: MoqVideoRendition] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: MoqVideoRendition]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeMoqVideoRendition.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureMoqFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Connect to a MoQ server.
 *
 * `publish` and `consume` are optional origins for the respective directions.
 */
public func moqConnect(url: String, publish: MoqOrigin?, consume: MoqOrigin?)async throws  -> MoqSession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_moq_ffi_fn_func_moq_connect(FfiConverterString.lower(url),FfiConverterOptionTypeMoqOrigin.lower(publish),FfiConverterOptionTypeMoqOrigin.lower(consume)
                )
            },
            pollFunc: ffi_moq_ffi_rust_future_poll_u64,
            completeFunc: ffi_moq_ffi_rust_future_complete_u64,
            freeFunc: ffi_moq_ffi_rust_future_free_u64,
            liftFunc: FfiConverterTypeMoqSession_lift,
            errorHandler: FfiConverterTypeMoqError_lift
        )
}
/**
 * Initialize logging with a level string: "error", "warn", "info", "debug", "trace", or "".
 */
public func moqLogLevel(level: String)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_log_level(
        FfiConverterString.lower(level),$0
    )
}
}
/**
 * Create a new origin for publishing and/or consuming broadcasts.
 */
public func moqOriginCreate() -> MoqOrigin  {
    return try!  FfiConverterTypeMoqOrigin_lift(try! rustCall() {
    uniffi_moq_ffi_fn_func_moq_origin_create($0
    )
})
}
/**
 * Create a new broadcast for publishing media tracks.
 */
public func moqPublishCreate()throws  -> MoqPublisher  {
    return try  FfiConverterTypeMoqPublisher_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_create($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_moq_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_connect() != 2362) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_log_level() != 55587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_create() != 47301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_create() != 6174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqannounced_next() != 26814) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqbroadcast_catalog() != 38614) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqbroadcast_subscribe_track() != 54522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqcatalogstream_next() != 33056) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqmedia_finish() != 54605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqmedia_write_frame() != 44640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqorigin_announced() != 62231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqorigin_consume() != 1304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqorigin_publish() != 60848) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqpublisher_media_ordered() != 32403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqsession_closed() != 18448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqsession_disconnect() != 6767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqtrack_next() != 58243) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_moqtrack_unsubscribe() != 53690) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMoqFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all