// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(moqFFI)
import moqFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_moq_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_moq_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMoqFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * A broadcast announced by an origin.
 */
public struct AnnouncedInfo: Equatable, Hashable {
    public var path: String
    public var active: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, active: Bool) {
        self.path = path
        self.active = active
    }

    

    
}

#if compiler(>=6)
extension AnnouncedInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnnouncedInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnnouncedInfo {
        return
            try AnnouncedInfo(
                path: FfiConverterString.read(from: &buf), 
                active: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AnnouncedInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterBool.write(value.active, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnouncedInfo_lift(_ buf: RustBuffer) throws -> AnnouncedInfo {
    return try FfiConverterTypeAnnouncedInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnouncedInfo_lower(_ value: AnnouncedInfo) -> RustBuffer {
    return FfiConverterTypeAnnouncedInfo.lower(value)
}


/**
 * Information about an audio rendition in the catalog.
 */
public struct AudioConfig: Equatable, Hashable {
    public var name: String
    public var codec: String
    public var description: Data?
    public var sampleRate: UInt32
    public var channelCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, codec: String, description: Data?, sampleRate: UInt32, channelCount: UInt32) {
        self.name = name
        self.codec = codec
        self.description = description
        self.sampleRate = sampleRate
        self.channelCount = channelCount
    }

    

    
}

#if compiler(>=6)
extension AudioConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioConfig {
        return
            try AudioConfig(
                name: FfiConverterString.read(from: &buf), 
                codec: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionData.read(from: &buf), 
                sampleRate: FfiConverterUInt32.read(from: &buf), 
                channelCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: AudioConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.codec, into: &buf)
        FfiConverterOptionData.write(value.description, into: &buf)
        FfiConverterUInt32.write(value.sampleRate, into: &buf)
        FfiConverterUInt32.write(value.channelCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioConfig_lift(_ buf: RustBuffer) throws -> AudioConfig {
    return try FfiConverterTypeAudioConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioConfig_lower(_ value: AudioConfig) -> RustBuffer {
    return FfiConverterTypeAudioConfig.lower(value)
}


/**
 * A decoded media frame.
 */
public struct FrameData: Equatable, Hashable {
    public var payload: Data
    public var timestampUs: UInt64
    public var keyframe: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(payload: Data, timestampUs: UInt64, keyframe: Bool) {
        self.payload = payload
        self.timestampUs = timestampUs
        self.keyframe = keyframe
    }

    

    
}

#if compiler(>=6)
extension FrameData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrameData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrameData {
        return
            try FrameData(
                payload: FfiConverterData.read(from: &buf), 
                timestampUs: FfiConverterUInt64.read(from: &buf), 
                keyframe: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FrameData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterUInt64.write(value.timestampUs, into: &buf)
        FfiConverterBool.write(value.keyframe, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameData_lift(_ buf: RustBuffer) throws -> FrameData {
    return try FfiConverterTypeFrameData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameData_lower(_ value: FrameData) -> RustBuffer {
    return FfiConverterTypeFrameData.lower(value)
}


/**
 * Information about a video rendition in the catalog.
 */
public struct VideoConfig: Equatable, Hashable {
    public var name: String
    public var codec: String
    public var description: Data?
    public var codedWidth: UInt32?
    public var codedHeight: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, codec: String, description: Data?, codedWidth: UInt32?, codedHeight: UInt32?) {
        self.name = name
        self.codec = codec
        self.description = description
        self.codedWidth = codedWidth
        self.codedHeight = codedHeight
    }

    

    
}

#if compiler(>=6)
extension VideoConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVideoConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VideoConfig {
        return
            try VideoConfig(
                name: FfiConverterString.read(from: &buf), 
                codec: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionData.read(from: &buf), 
                codedWidth: FfiConverterOptionUInt32.read(from: &buf), 
                codedHeight: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: VideoConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.codec, into: &buf)
        FfiConverterOptionData.write(value.description, into: &buf)
        FfiConverterOptionUInt32.write(value.codedWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.codedHeight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVideoConfig_lift(_ buf: RustBuffer) throws -> VideoConfig {
    return try FfiConverterTypeVideoConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVideoConfig_lower(_ value: VideoConfig) -> RustBuffer {
    return FfiConverterTypeVideoConfig.lower(value)
}


/**
 * Error returned by all UniFFI-exported functions.
 */
public enum MoqError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Error(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MoqError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoqError: FfiConverterRustBuffer {
    typealias SwiftType = MoqError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoqError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Error(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MoqError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Error(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqError_lift(_ buf: RustBuffer) throws -> MoqError {
    return try FfiConverterTypeMoqError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoqError_lower(_ value: MoqError) -> RustBuffer {
    return FfiConverterTypeMoqError.lower(value)
}




/**
 * Callback invoked when a broadcast is announced by an origin.
 */
public protocol AnnounceCallback: AnyObject, Sendable {
    
    func onAnnounce(announcedId: Int32) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAnnounceCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceAnnounceCallback] = [UniffiVTableCallbackInterfaceAnnounceCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceAnnounceCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AnnounceCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceAnnounceCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AnnounceCallback: handle missing in uniffiClone")
            }
        },
        onAnnounce: { (
            uniffiHandle: UInt64,
            announcedId: Int32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAnnounceCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onAnnounce(
                     announcedId: try FfiConverterInt32.lift(announcedId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitAnnounceCallback() {
    uniffi_moq_ffi_fn_init_callback_vtable_announcecallback(UniffiCallbackInterfaceAnnounceCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAnnounceCallback {
    fileprivate static let handleMap = UniffiHandleMap<AnnounceCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAnnounceCallback : FfiConverter {
    typealias SwiftType = AnnounceCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAnnounceCallback_lift(_ handle: UInt64) throws -> AnnounceCallback {
    return try FfiConverterCallbackInterfaceAnnounceCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAnnounceCallback_lower(_ v: AnnounceCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceAnnounceCallback.lower(v)
}




/**
 * Callback invoked when a new catalog is available on a broadcast.
 */
public protocol CatalogCallback: AnyObject, Sendable {
    
    func onCatalog(catalogId: Int32) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCatalogCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceCatalogCallback] = [UniffiVTableCallbackInterfaceCatalogCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceCatalogCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface CatalogCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceCatalogCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface CatalogCallback: handle missing in uniffiClone")
            }
        },
        onCatalog: { (
            uniffiHandle: UInt64,
            catalogId: Int32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCatalogCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onCatalog(
                     catalogId: try FfiConverterInt32.lift(catalogId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitCatalogCallback() {
    uniffi_moq_ffi_fn_init_callback_vtable_catalogcallback(UniffiCallbackInterfaceCatalogCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceCatalogCallback {
    fileprivate static let handleMap = UniffiHandleMap<CatalogCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceCatalogCallback : FfiConverter {
    typealias SwiftType = CatalogCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCatalogCallback_lift(_ handle: UInt64) throws -> CatalogCallback {
    return try FfiConverterCallbackInterfaceCatalogCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCatalogCallback_lower(_ v: CatalogCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceCatalogCallback.lower(v)
}




/**
 * Callback invoked when a new frame is available on a track.
 */
public protocol FrameCallback: AnyObject, Sendable {
    
    func onFrame(frameId: Int32) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFrameCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceFrameCallback] = [UniffiVTableCallbackInterfaceFrameCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceFrameCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface FrameCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceFrameCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface FrameCallback: handle missing in uniffiClone")
            }
        },
        onFrame: { (
            uniffiHandle: UInt64,
            frameId: Int32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onFrame(
                     frameId: try FfiConverterInt32.lift(frameId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitFrameCallback() {
    uniffi_moq_ffi_fn_init_callback_vtable_framecallback(UniffiCallbackInterfaceFrameCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFrameCallback {
    fileprivate static let handleMap = UniffiHandleMap<FrameCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFrameCallback : FfiConverter {
    typealias SwiftType = FrameCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceFrameCallback_lift(_ handle: UInt64) throws -> FrameCallback {
    return try FfiConverterCallbackInterfaceFrameCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceFrameCallback_lower(_ v: FrameCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceFrameCallback.lower(v)
}




/**
 * Callback invoked when a session's status changes.
 */
public protocol SessionCallback: AnyObject, Sendable {
    
    func onStatus(code: Int32) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSessionCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceSessionCallback] = [UniffiVTableCallbackInterfaceSessionCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSessionCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SessionCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSessionCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SessionCallback: handle missing in uniffiClone")
            }
        },
        onStatus: { (
            uniffiHandle: UInt64,
            code: Int32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSessionCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStatus(
                     code: try FfiConverterInt32.lift(code)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitSessionCallback() {
    uniffi_moq_ffi_fn_init_callback_vtable_sessioncallback(UniffiCallbackInterfaceSessionCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSessionCallback {
    fileprivate static let handleMap = UniffiHandleMap<SessionCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSessionCallback : FfiConverter {
    typealias SwiftType = SessionCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSessionCallback_lift(_ handle: UInt64) throws -> SessionCallback {
    return try FfiConverterCallbackInterfaceSessionCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSessionCallback_lower(_ v: SessionCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceSessionCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * Close an audio track consumer and cancel its background task.
 */
public func moqConsumeAudioClose(track: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_audio_close(
        FfiConverterUInt32.lower(track),$0
    )
}
}
/**
 * Query information about an audio track in a catalog.
 */
public func moqConsumeAudioConfig(catalog: UInt32, index: UInt32)throws  -> AudioConfig  {
    return try  FfiConverterTypeAudioConfig_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_audio_config(
        FfiConverterUInt32.lower(catalog),
        FfiConverterUInt32.lower(index),$0
    )
})
}
/**
 * Consume an audio track from a catalog, delivering frames in decode order.
 *
 * `max_latency_ms` controls the maximum buffering before skipping frames.
 * The callback receives a `frame_id` when each frame is available.
 * Returns a non-zero handle that can be passed to [`moq_consume_audio_close`].
 */
public func moqConsumeAudioOrdered(catalog: UInt32, index: UInt32, maxLatencyMs: UInt64, callback: FrameCallback)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_audio_ordered(
        FfiConverterUInt32.lower(catalog),
        FfiConverterUInt32.lower(index),
        FfiConverterUInt64.lower(maxLatencyMs),
        FfiConverterCallbackInterfaceFrameCallback_lower(callback),$0
    )
})
}
/**
 * Create a catalog consumer for a broadcast.
 *
 * The callback receives a `catalog_id` when a new catalog becomes available.
 * Returns a non-zero handle that can be passed to [`moq_consume_catalog_close`].
 */
public func moqConsumeCatalog(broadcast: UInt32, callback: CatalogCallback)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_catalog(
        FfiConverterUInt32.lower(broadcast),
        FfiConverterCallbackInterfaceCatalogCallback_lower(callback),$0
    )
})
}
/**
 * Close a catalog consumer and cancel its background task.
 */
public func moqConsumeCatalogClose(catalog: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_catalog_close(
        FfiConverterUInt32.lower(catalog),$0
    )
}
}
/**
 * Close a catalog snapshot received via the catalog callback.
 */
public func moqConsumeCatalogFree(catalog: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_catalog_free(
        FfiConverterUInt32.lower(catalog),$0
    )
}
}
/**
 * Close a broadcast consumer and clean up its resources.
 */
public func moqConsumeClose(consume: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_close(
        FfiConverterUInt32.lower(consume),$0
    )
}
}
/**
 * Retrieve the full payload and metadata for a frame.
 *
 * Returns a [`FrameData`] with the complete frame payload allocated as a `Vec<u8>`.
 * Call [`moq_consume_frame_close`] when done.
 */
public func moqConsumeFrame(frame: UInt32)throws  -> FrameData  {
    return try  FfiConverterTypeFrameData_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_frame(
        FfiConverterUInt32.lower(frame),$0
    )
})
}
/**
 * Close a frame and free its resources.
 */
public func moqConsumeFrameClose(frame: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_frame_close(
        FfiConverterUInt32.lower(frame),$0
    )
}
}
/**
 * Close a video track consumer and cancel its background task.
 */
public func moqConsumeVideoClose(track: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_video_close(
        FfiConverterUInt32.lower(track),$0
    )
}
}
/**
 * Query information about a video track in a catalog.
 */
public func moqConsumeVideoConfig(catalog: UInt32, index: UInt32)throws  -> VideoConfig  {
    return try  FfiConverterTypeVideoConfig_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_video_config(
        FfiConverterUInt32.lower(catalog),
        FfiConverterUInt32.lower(index),$0
    )
})
}
/**
 * Consume a video track from a catalog, delivering frames in decode order.
 *
 * `max_latency_ms` controls the maximum buffering before skipping a GoP.
 * The callback receives a `frame_id` when each frame is available.
 * Returns a non-zero handle that can be passed to [`moq_consume_video_close`].
 */
public func moqConsumeVideoOrdered(catalog: UInt32, index: UInt32, maxLatencyMs: UInt64, callback: FrameCallback)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_consume_video_ordered(
        FfiConverterUInt32.lower(catalog),
        FfiConverterUInt32.lower(index),
        FfiConverterUInt64.lower(maxLatencyMs),
        FfiConverterCallbackInterfaceFrameCallback_lower(callback),$0
    )
})
}
/**
 * Initialize the library with a log level.
 *
 * Should be called before any other functions.
 * The `level` string may be: `"error"`, `"warn"`, `"info"`, `"debug"`, or `"trace"`.
 */
public func moqLogLevel(level: String)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_log_level(
        FfiConverterString.lower(level),$0
    )
}
}
/**
 * Subscribe to broadcast announcements on an origin.
 *
 * The callback receives an `announced_id` for each new announcement.
 * Returns a non-zero handle that can be passed to [`moq_origin_announced_close`].
 */
public func moqOriginAnnounced(origin: UInt32, callback: AnnounceCallback)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_announced(
        FfiConverterUInt32.lower(origin),
        FfiConverterCallbackInterfaceAnnounceCallback_lower(callback),$0
    )
})
}
/**
 * Stop receiving announcements for broadcasts published to an origin.
 */
public func moqOriginAnnouncedClose(announced: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_announced_close(
        FfiConverterUInt32.lower(announced),$0
    )
}
}
/**
 * Query information about a discovered broadcast announcement.
 */
public func moqOriginAnnouncedInfo(announced: UInt32)throws  -> AnnouncedInfo  {
    return try  FfiConverterTypeAnnouncedInfo_lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_announced_info(
        FfiConverterUInt32.lower(announced),$0
    )
})
}
/**
 * Close an origin and clean up its resources.
 */
public func moqOriginClose(origin: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_close(
        FfiConverterUInt32.lower(origin),$0
    )
}
}
/**
 * Consume a broadcast from an origin by path.
 *
 * Returns a non-zero handle to the broadcast consumer.
 */
public func moqOriginConsume(origin: UInt32, path: String)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_consume(
        FfiConverterUInt32.lower(origin),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Create an origin for publishing and/or consuming broadcasts.
 *
 * Returns a non-zero handle to the origin.
 */
public func moqOriginCreate()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_create($0
    )
})
}
/**
 * Publish a broadcast to an origin under the given path.
 */
public func moqOriginPublish(origin: UInt32, path: String, broadcast: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_origin_publish(
        FfiConverterUInt32.lower(origin),
        FfiConverterString.lower(path),
        FfiConverterUInt32.lower(broadcast),$0
    )
}
}
/**
 * Close a broadcast and clean up its resources.
 */
public func moqPublishClose(broadcast: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_close(
        FfiConverterUInt32.lower(broadcast),$0
    )
}
}
/**
 * Create a new broadcast for publishing media tracks.
 *
 * Returns a non-zero handle to the broadcast.
 */
public func moqPublishCreate()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_create($0
    )
})
}
/**
 * Remove a track from a broadcast and clean up its resources.
 */
public func moqPublishMediaClose(media: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_media_close(
        FfiConverterUInt32.lower(media),$0
    )
}
}
/**
 * Write a frame to a media track.
 *
 * `timestamp_us` is the presentation timestamp in microseconds.
 */
public func moqPublishMediaFrame(media: UInt32, payload: Data, timestampUs: UInt64)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_media_frame(
        FfiConverterUInt32.lower(media),
        FfiConverterData.lower(payload),
        FfiConverterUInt64.lower(timestampUs),$0
    )
}
}
/**
 * Create a new media track for a broadcast.
 *
 * `format` controls the encoding of `init` and frame payloads.
 * Returns a non-zero handle to the media track.
 */
public func moqPublishMediaOrdered(broadcast: UInt32, format: String, `init`: Data)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_publish_media_ordered(
        FfiConverterUInt32.lower(broadcast),
        FfiConverterString.lower(format),
        FfiConverterData.lower(`init`),$0
    )
})
}
/**
 * Close a session and free its resources.
 */
public func moqSessionClose(session: UInt32)throws   {try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_session_close(
        FfiConverterUInt32.lower(session),$0
    )
}
}
/**
 * Start establishing a connection to a MoQ server.
 *
 * Returns a non-zero handle to the session on success.
 * `origin_publish` and `origin_consume` are origin handles (0 = disabled).
 * The callback receives status 0 on connect and a non-zero code on close/error.
 */
public func moqSessionConnect(url: String, originPublish: UInt32, originConsume: UInt32, callback: SessionCallback)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMoqError_lift) {
    uniffi_moq_ffi_fn_func_moq_session_connect(
        FfiConverterString.lower(url),
        FfiConverterUInt32.lower(originPublish),
        FfiConverterUInt32.lower(originConsume),
        FfiConverterCallbackInterfaceSessionCallback_lower(callback),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_moq_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_audio_close() != 40766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_audio_config() != 28165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_audio_ordered() != 4893) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_catalog() != 29400) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_catalog_close() != 6165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_catalog_free() != 57856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_close() != 59181) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_frame() != 52462) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_frame_close() != 28083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_video_close() != 31594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_video_config() != 25849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_consume_video_ordered() != 38110) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_log_level() != 14349) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_announced() != 28213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_announced_close() != 40716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_announced_info() != 24231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_close() != 49817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_consume() != 26396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_create() != 34132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_origin_publish() != 37281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_close() != 28305) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_create() != 54564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_media_close() != 61399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_media_frame() != 46970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_publish_media_ordered() != 11878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_session_close() != 5253) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_func_moq_session_connect() != 34068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_announcecallback_on_announce() != 24954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_catalogcallback_on_catalog() != 33062) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_framecallback_on_frame() != 9285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_moq_ffi_checksum_method_sessioncallback_on_status() != 449) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAnnounceCallback()
    uniffiCallbackInitCatalogCallback()
    uniffiCallbackInitFrameCallback()
    uniffiCallbackInitSessionCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMoqFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all