package com.swmansion.moqkit.publish

import com.swmansion.moqkit.publish.source.PublishControl
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import com.swmansion.moqkit.UnsupportedCodecException
import com.swmansion.moqkit.publish.encoder.AudioEncoder
import com.swmansion.moqkit.publish.encoder.AudioEncoderConfig
import com.swmansion.moqkit.publish.encoder.VideoEncoder
import com.swmansion.moqkit.publish.encoder.VideoEncoderConfig
import com.swmansion.moqkit.publish.source.AudioFrameSource
import com.swmansion.moqkit.publish.source.CaptureLifecycle
import com.swmansion.moqkit.publish.source.CaptureTrackBinding
import com.swmansion.moqkit.publish.source.CameraCapture
import com.swmansion.moqkit.publish.source.MicrophoneCapture
import com.swmansion.moqkit.publish.source.VideoFrameSource
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import dev.moq.BroadcastProducer
import dev.moq.TrackProducer

/**
 * Collects tracks and publishes them as one broadcast.
 *
 * Add all tracks before calling [start]. A publisher is usually registered with
 * [com.swmansion.moqkit.Session.publish] first, then started:
 *
 * ```kotlin
 * val publisher = Publisher()
 * publisher.addVideoTrack(name = "camera", source = camera)
 * publisher.addAudioTrack(name = "mic", source = microphone)
 * session.publish(path = "live/android", publisher = publisher)
 * publisher.start()
 * ```
 *
 * Call [stop] when the broadcast should end. A stopped publisher should not be reused;
 * create a new [Publisher] for the next broadcast.
 */
class Publisher {
    private var registrationClosed = false
    private val _state = MutableStateFlow<PublisherState>(PublisherState.Idle)

    /** Current publishing state. */
    val state: StateFlow<PublisherState> = _state.asStateFlow()

    private val _events = MutableSharedFlow<PublisherEvent>(extraBufferCapacity = 16)

    /**
     * Track-level events useful for updating UI or surfacing publish errors.
     */
    val events: SharedFlow<PublisherEvent> = _events

    // Created by Session.publish() at the broadcast path; tracks cannot start without it.
    internal var broadcast: BroadcastProducer? = null
        private set
    internal val clock = Clock()

    @Synchronized
    internal fun attachBroadcast(broadcast: BroadcastProducer) {
        check(_state.value == PublisherState.Idle && this.broadcast == null) { "Publisher is already registered with a session" }
        this.broadcast = broadcast
    }

    // Descriptors registered before start()
    private val videoDescriptors = mutableListOf<VideoTrackDescriptor>()
    private val audioDescriptors = mutableListOf<AudioTrackDescriptor>()
    private val dataDescriptors = mutableListOf<DataTrackDescriptor>()

    // Active runtime state
    private val activeDataTracks = mutableMapOf<String, ActiveDataTrack>()

    /**
     * Adds a video track backed by a [VideoFrameSource].
     *
     * Built-in sources include [com.swmansion.moqkit.publish.source.CameraCapture],
     * [com.swmansion.moqkit.publish.source.MultiCameraCapture], and
     * [com.swmansion.moqkit.publish.source.ScreenCapture]. The track starts only after
     * [start] is called.
     *
     * @param name Local SDK label used by [PublishedTrack] and [PublisherEvent]. Media
     *   catalog track names are generated by the underlying muxer; discover them from
     *   `Catalog.videoTracks`. Names must be unique among video tracks in this publisher.
     * @param source Video source that will feed encoder frames.
     * @param config Encoder settings and codec choice.
     * @return A handle for observing or stopping this track.
     * @throws IllegalArgumentException if another video track already uses [name].
     */
    @Synchronized
    fun addVideoTrack(
        name: String = "video",
        source: VideoFrameSource,
        config: VideoEncoderConfig = VideoEncoderConfig(),
        enabled: Boolean = true,
    ): PublishedMediaTrack {
        validateRegistration(name)
        val track = PublishedMediaTrack(
            enabled = enabled,
            name = name,
            codecInfo = TrackCodecInfo.Video(config.codec, config.width, config.height, config.frameRate),
        )
        reserveSource(source, track)
        videoDescriptors.add(VideoTrackDescriptor(track, source, config))
        return track
    }

    /**
     * Adds an audio track backed by an [AudioFrameSource].
     *
     * Built-in sources include [com.swmansion.moqkit.publish.source.MicrophoneCapture].
     * The track starts only after [start] is called.
     *
     * @param name Local SDK label used by [PublishedTrack] and [PublisherEvent]. Media
     *   catalog track names are generated by the underlying muxer; discover them from
     *   `Catalog.audioTracks`. Names must be unique among audio tracks in this publisher.
     * @param source Audio source that provides PCM samples.
     * @param config Encoder settings and codec choice.
     * @return A handle for observing or stopping this track.
     * @throws IllegalArgumentException if another audio track already uses [name].
     */
    @Synchronized
    fun addAudioTrack(
        name: String = "audio",
        source: AudioFrameSource,
        config: AudioEncoderConfig = AudioEncoderConfig(),
        enabled: Boolean = true,
    ): PublishedMediaTrack {
        validateRegistration(name)
        val track = PublishedMediaTrack(
            enabled = enabled,
            name = name,
            codecInfo = TrackCodecInfo.Audio(config.codec, config.sampleRate),
        )
        reserveSource(source, track)
        audioDescriptors.add(AudioTrackDescriptor(track, source, config))
        return track
    }

    /**
     * Adds a raw data track.
     *
     * Data tracks send application-defined binary payloads, such as JSON chat messages.
     * They do not need to appear in the media catalog and are read with
     * [com.swmansion.moqkit.subscribe.Broadcast.subscribeTrack].
     *
     * @param name Track name used by subscribers.
     * @param emitter Object used to send payloads after [start].
     * @return A handle for observing or stopping this track.
     * @throws IllegalArgumentException if another data track already uses [name].
     */
    @Synchronized
    fun addDataTrack(
        name: String = "data",
        emitter: DataTrackEmitter,
    ): PublishedTrack {
        validateRegistration(name)
        val track = PublishedTrack(name = name, codecInfo = TrackCodecInfo.Data)
        dataDescriptors.add(DataTrackDescriptor(track, emitter))
        return track
    }

    /**
     * Attaches registered tracks. Enabled camera/microphone tracks wait for source availability.
     * Codec support is checked when each encoder is needed; unsupported disabled/stopped
     * sources do not prevent other media from publishing.
     *
     * @throws IllegalStateException if this publisher has already been started or has not
     *   been registered with [com.swmansion.moqkit.Session.publish] yet.
     * @throws UnsupportedCodecException if any configured media track cannot be encoded on
     *   this device.
     */
    suspend fun start() {
        currentCoroutineContext().ensureActive()
        PublishControl.run {
            val broadcast = synchronized(this) {
                check(!registrationClosed && _state.value == PublisherState.Idle) { "Publisher already started" }
                checkNotNull(broadcast) { "Register with Session.publish() before start()" }
                    .also { registrationClosed = true }
            }
            try {
                videoDescriptors.filter { it.track.state.value != PublishedTrackState.Stopped }
                    .forEach { startVideoTrack(it, broadcast) }
                audioDescriptors.filter { it.track.state.value != PublishedTrackState.Stopped }
                    .forEach { startAudioTrack(it, broadcast) }
                dataDescriptors.filter { it.track.state.value != PublishedTrackState.Stopped }
                    .forEach { startDataTrack(it, broadcast) }
                _state.value = PublisherState.Publishing
            } catch (e: Exception) {
                stopOwned()
                _state.value = PublisherState.Error(e.message ?: "Publisher start failed")
                throw e
            }
        }
    }

    /** End the broadcast and await encoder teardown. Capture and preview continue. */
    suspend fun stop() = PublishControl.run { stopOwned() }

    private fun stopOwned() {
        if (_state.value == PublisherState.Stopped) return
        synchronized(this) { registrationClosed = true }
        videoDescriptors.forEach { it.track.stopOwned() }
        audioDescriptors.forEach { it.track.stopOwned() }
        dataDescriptors.forEach { it.track.stopOwned() }
        activeDataTracks.clear()
        try { broadcast?.finish() } catch (_: Exception) {}
        broadcast?.close()
        broadcast = null
        clock.reset()
        _state.value = PublisherState.Stopped
    }

    private fun validateRegistration(name: String) {
        check(!registrationClosed && _state.value == PublisherState.Idle) { "Add tracks before Publisher.start()" }
        require((videoDescriptors.map { it.track.name } + audioDescriptors.map { it.track.name } +
            dataDescriptors.map { it.track.name }).none { it == name }) { "Duplicate track name: $name" }
    }

    private fun reserveSource(source: Any, track: PublishedMediaTrack) {
        val lifecycle = captureLifecycle(source)
        val owner = Any()
        lifecycle?.reserve(owner)
        track.releaseAction = { lifecycle?.release(owner) }
        track.stopAction = {
            track.outputID = null
            track.binding?.stop()
            track.binding = null
            _events.tryEmit(PublisherEvent.TrackStopped(track.name))
        }
    }

    private fun captureLifecycle(source: Any): CaptureLifecycle? = when (source) {
        is CameraCapture -> source.captureLifecycle
        is MicrophoneCapture -> source.captureLifecycle
        else -> null
    }

    private fun mediaOutput(track: PublishedMediaTrack, broadcast: BroadcastProducer, format: String): MediaTrackOutput {
        val id = Any()
        track.outputID = id
        return MediaTrackOutput(
            broadcast, format,
            onActive = {
                PublishControl.post {
                    if (track.outputID === id) {
                        track.transition(PublishedTrackState.Active)
                        _events.tryEmit(PublisherEvent.TrackStarted(track.name))
                    }
                }
            },
            onError = { error ->
                PublishControl.post { if (track.outputID === id) track.binding?.fail(error) }
            },
        )
    }

    private fun startVideoTrack(desc: VideoTrackDescriptor, broadcast: BroadcastProducer) {
        val track = desc.track
        val binding = CaptureTrackBinding(
            enabled = track.isEnabled,
            start = {
                desc.config.unsupportedReason?.let { throw UnsupportedCodecException(it) }
                val encoder = VideoEncoder(desc.config)
                val output = mediaOutput(track, broadcast, desc.config.format)
                track.transition(PublishedTrackState.Starting)
                try {
                    encoder.start(onError = output::fail) { frame ->
                        output.write(frame.data, frame.initData, clock.timestampUs(frame.timestampUs))
                    }
                    encoder.encoderInputSurface?.let { desc.source.attachEncoderSurface(it) }
                } catch (e: Exception) {
                    output.finish()
                    try { desc.source.detachEncoderSurface() } finally { encoder.stop() }
                    throw e
                }
                val stop: () -> Unit = {
                    track.outputID = null
                    output.finish()
                    try { desc.source.detachEncoderSurface() } finally { encoder.stop() }
                }
                stop
            },
            onState = { track.transition(it) },
            onClosed = { track.stopOwned() },
            onError = { error ->
                _events.tryEmit(PublisherEvent.TrackError(track.name, error.message ?: "encoder start failed"))
            },
        )
        track.binding = binding
        binding.attach(captureLifecycle(desc.source))
    }

    private fun startAudioTrack(desc: AudioTrackDescriptor, broadcast: BroadcastProducer) {
        val track = desc.track
        val binding = CaptureTrackBinding(
            enabled = track.isEnabled,
            start = {
                desc.config.unsupportedReason?.let { throw UnsupportedCodecException(it) }
                val encoder = AudioEncoder(desc.config)
                val output = mediaOutput(track, broadcast, desc.config.format)
                track.transition(PublishedTrackState.Starting)
                try {
                    encoder.start(desc.source, onError = output::fail) { frame ->
                        output.write(frame.data, frame.initData, clock.timestampUs(frame.timestampUs))
                    }
                } catch (e: Exception) {
                    output.finish()
                    desc.source.onPcmData = null
                    encoder.stop()
                    throw e
                }
                val stop: () -> Unit = {
                    track.outputID = null
                    output.finish()
                    desc.source.onPcmData = null
                    encoder.stop()
                }
                stop
            },
            onState = { track.transition(it) },
            onClosed = { track.stopOwned() },
            onError = { error ->
                _events.tryEmit(PublisherEvent.TrackError(track.name, error.message ?: "encoder start failed"))
            },
        )
        track.binding = binding
        binding.attach(captureLifecycle(desc.source))
    }

    // MARK: - Data

    private fun startDataTrack(desc: DataTrackDescriptor, broadcast: BroadcastProducer) {
        val producer = broadcast.publishTrack(desc.track.name, null)
        val active = ActiveDataTrack(desc.emitter, producer)
        desc.emitter.attach(producer, clock)

        val trackHandle = desc.track
        trackHandle.stopAction = {
            tearDownDataTrack(active)
            activeDataTracks.remove(trackHandle.name)
            trackHandle.transition(PublishedTrackState.Stopped)
            _events.tryEmit(PublisherEvent.TrackStopped(trackHandle.name))
        }

        activeDataTracks[desc.track.name] = active
        trackHandle.transition(PublishedTrackState.Active)
        _events.tryEmit(PublisherEvent.TrackStarted(trackHandle.name))
    }

    private fun tearDownDataTrack(active: ActiveDataTrack) {
        active.emitter?.detach()
        try { active.producer?.finish() } catch (_: Exception) {}
        try { active.producer?.close() } catch (_: Exception) {}
    }

    // MARK: - Internal descriptor / runtime types

    private data class VideoTrackDescriptor(
        val track: PublishedMediaTrack,
        val source: VideoFrameSource,
        val config: VideoEncoderConfig,
    )

    private data class AudioTrackDescriptor(
        val track: PublishedMediaTrack,
        val source: AudioFrameSource,
        val config: AudioEncoderConfig,
    )

    private data class DataTrackDescriptor(
        val track: PublishedTrack,
        val emitter: DataTrackEmitter,
    )

    private data class ActiveDataTrack(
        val emitter: DataTrackEmitter?,
        val producer: TrackProducer?,
    )
}
