#!/usr/bin/env bash
set -euo pipefail

# Build libmoq for iOS targets and package as an XCFramework.
#
# Usage: ./scripts/build-xcframework.sh [--debug]
#
#   --debug  Build with debug symbols (release-with-debug profile: optimized + DWARF)
#
# Produces: ios/Frameworks/Clibmoq.xcframework/

DEBUG=0
for arg in "$@"; do
    case "$arg" in
        --debug) DEBUG=1 ;;
        *) echo "Unknown argument: $arg" >&2; exit 1 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_CARGO="$ROOT_DIR/vendor/moq/Cargo.toml"
TARGET_BASE="$ROOT_DIR/vendor/moq/target"
OUTPUT_DIR="$ROOT_DIR/ios/Frameworks"
XCFRAMEWORK="$OUTPUT_DIR/Clibmoq.xcframework"

TARGETS=(
    aarch64-apple-ios
    aarch64-apple-ios-sim
)

# --- Install Rust targets if missing ---

echo "Checking Rust targets..."
INSTALLED=$(rustup target list --installed)
for target in "${TARGETS[@]}"; do
    if ! echo "$INSTALLED" | grep -q "^${target}$"; then
        echo "Installing Rust target: $target"
        rustup target add "$target"
    fi
done

# --- Build for each target ---

# Set iOS deployment target so aws-lc-sys C/asm build matches the Rust linker target.
# Without this, Xcode defaults to the current SDK version (e.g. 26.2), producing
# objects that reference ___chkstk_darwin — a symbol unavailable at iOS 10.0,
# which is what aarch64-apple-ios links against by default.
export IPHONEOS_DEPLOYMENT_TARGET=16.0

if [[ $DEBUG -eq 1 ]]; then
    CARGO_PROFILE="release-with-debug"
    PROFILE_FLAGS="--profile release-with-debug"
    echo "Building with debug symbols (profile: release-with-debug)"
else
    CARGO_PROFILE="release"
    PROFILE_FLAGS="--release"
fi

for target in "${TARGETS[@]}"; do
    echo "Building libmoq for $target..."
    cargo build $PROFILE_FLAGS --package libmoq --target "$target" \
        --manifest-path "$WORKSPACE_CARGO"
done

# --- Prepare headers ---

# The header is generated by build.rs into target/{target}/include/moq.h
# Use the device build as the reference (headers are identical across targets).
REF_TARGET="${TARGETS[0]}"
HEADER_SOURCE="$TARGET_BASE/$REF_TARGET/include/moq.h"

if [[ ! -f "$HEADER_SOURCE" ]]; then
    echo "Error: moq.h not found at $HEADER_SOURCE" >&2
    exit 1
fi

HEADERS_DIR="$ROOT_DIR/.build/headers"
rm -rf "$HEADERS_DIR"
mkdir -p "$HEADERS_DIR"
cp "$HEADER_SOURCE" "$HEADERS_DIR/moq.h"

cat > "$HEADERS_DIR/module.modulemap" <<'EOF'
module Clibmoq {
    header "moq.h"
    export *
}
EOF

# --- Create XCFramework ---

rm -rf "$XCFRAMEWORK"
mkdir -p "$OUTPUT_DIR"

DEVICE_LIB="$TARGET_BASE/aarch64-apple-ios/$CARGO_PROFILE/libmoq.a"
SIMULATOR_LIB="$TARGET_BASE/aarch64-apple-ios-sim/$CARGO_PROFILE/libmoq.a"

echo "Creating XCFramework..."
xcodebuild -create-xcframework \
    -library "$DEVICE_LIB" -headers "$HEADERS_DIR" \
    -library "$SIMULATOR_LIB" -headers "$HEADERS_DIR" \
    -output "$XCFRAMEWORK"

# --- Clean up ---

rm -rf "$ROOT_DIR/.build/headers"

echo ""
echo "XCFramework created at: $XCFRAMEWORK"
