import Foundation
import MoqFFI

// MoqError is generated by UniFFI into moq.swift.
// SessionError wraps higher-level session/codec errors.

extension SessionError: LocalizedError, CustomStringConvertible {
    public var errorDescription: String? {
        description
    }

    public var description: String {
        switch self {
        case .unsupportedCodec(let codec):
            return "Unsupported codec: \(codec)"
        case .missingCodecDescription:
            return "Codec description is required"
        case .formatDescriptionFailed(let status):
            return "Format description creation failed with status \(status)"
        case .sampleBufferFailed(let status):
            return "Sample buffer creation failed with status \(status)"
        case .alreadyConnected:
            return "Session is already connecting or connected"
        case .alreadyClosed:
            return "Session is already closed"
        case .alreadySubscribed:
            return "Session is already subscribed to this prefix"
        case .noTracksAvailable:
            return "No tracks are available"
        case .noBroadcastAvailable:
            return "No broadcast is available"
        case .noTracksSelected:
            return "Select at least one audio or video track"
        case .invalidConfiguration(let message):
            return message
        case .audioDecoderFailed(let message):
            return "Audio decoder failed: \(message)"
        case .connectionFailed(let message):
            return "Failed to connect: \(message)"
        }
    }
}

extension MoqError {
    var moqKitMessage: String {
        let message: String
        switch self {
        case .Protocol(message: let value),
             .Media(message: let value),
             .Mux(message: let value),
             .Audio(message: let value),
             .Url(message: let value),
             .TimeOverflow(message: let value),
             .LogLevel(message: let value),
             .Task(message: let value),
             .Cancelled(message: let value),
             .Closed(message: let value),
             .Connect(message: let value),
             .Bind(message: let value),
             .Reject(message: let value),
             .AlreadyResponded(message: let value),
             .Codec(message: let value),
             .Unauthorized(message: let value),
             .Log(message: let value):
            message = value
        }

        let trimmed = message.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? String(reflecting: self) : trimmed
    }
}
